PREFIX semapv: <https://w3id.org/semapv/vocab/>
PREFIX owl:    <http://www.w3.org/2002/07/owl#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX UPHENO: <http://purl.obolibrary.org/obo/UPHENO_>

CONSTRUCT {
    ?x owl:equivalentClass ?y .
}
WHERE {
    ?x rdfs:subClassOf+ UPHENO:0001001 .
    ?x semapv:crossSpeciesExactMatch ?y .
}
